import MapSection from '@/app/components/map-section/MapSection';
import Section from '@/app/components/section/Section';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Map Route',
  description: 'Generated by create next app',
};

const mapPage = () => {
  return (
    <>
      <Section>
        <MapSection />
      </Section>
    </>
  );
};

export default mapPage;
